version: '3.0'
services:

  shopware5_web:
    image: proudcommerce/docker-php72-apache-stretch
    volumes:
      - ./web/www/:/var/www/html/:cached
      - ./web/logs/:/var/log/apache2/
    env_file:
      - app.env
    depends_on:
      - shopware5_mysql
    ports:
      - "80:80"

  shopware5_mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/:/var/lib/mysql
    env_file:
      - app.env
      - db.env
    ports:
      - "3306:3306"

  shopware5_mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"

  shopware5_phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "80:80"
    environment:
      PMA_HOST: shopware5_mysql

  sftp:
    image: atmoz/sftp
    volumes:
      - ./web/www/:/home/docker/
    ports:
      - "2222:22"
    command: docker:$$1$$Fee8MGyh$$pPX3wFp89lh1WmfFoe3ql/:e:::/home/docker