apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: shopware5-mysql
  name: shopware5-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopware5-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: shopware5-mysql
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: app-env
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_HOST
                  name: app-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: app-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: db-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: app-env
            - name: OXID_SHOP_DIR
              valueFrom:
                configMapKeyRef:
                  key: OXID_SHOP_DIR
                  name: app-env
            - name: OXID_SHOP_URL
              valueFrom:
                configMapKeyRef:
                  key: OXID_SHOP_URL
                  name: app-env
            - name: PS_APACHE_DOCROOT
              valueFrom:
                configMapKeyRef:
                  key: PS_APACHE_DOCROOT
                  name: app-env
            - name: PS_APACHE_SERVERADMIN
              valueFrom:
                configMapKeyRef:
                  key: PS_APACHE_SERVERADMIN
                  name: app-env
          image: mysql:5.7
          name: shopware5-mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: shopware5-mysql-claim0
      restartPolicy: Always
      volumes:
        - name: shopware5-mysql-claim0
          persistentVolumeClaim:
            claimName: shopware5-mysql-claim0
status: {}
